### PR TITLE
[WIP] first iteration on collapse/expand

### PR DESCRIPTION
**Pull request by Bedrock02**
## Proposed changes

Describe the changes you added.

Solves issue [44](https://github.com/blancahouse/casablanca/issues/44).

## Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you
did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Bedrock02** [comment]
Looking to get some feedback. Are there any examples that we are trying to replicate?

Also is there a way to import html into an .md file? I'd like to essentially have the expand/collapse link-component as a module I can import so that it is easy to set up on other pages

**Comment by fvntr** [comment]
@Bedrock02 not sure I understand the second part, do you mean something like this http://assemble.io/docs/Markdown.html

**Comment by Bedrock02** [comment]
@fvntr Want me to add the expand/collapse on the Executive orders? I wanted to get some feedback first.

and yes I believe that is what I am looking for. thanks

**Comment by fvntr** [comment]
@Bedrock02 yeah just to be consistent

**Pull request merged**
