### PR TITLE
Added expand/hide to existing press content

### PR DESCRIPTION
**Pull request by Bedrock02**
## Proposed changes

Describe the changes you added.

Solves issue [56](https://github.com/blancahouse/casablanca/issues/56).

## Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you
did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Bedrock02** [comment]
@fvntr I added missing collapse/expand.

Also I increased the height for when the content is hidden. Check it out let me know what you think would look good on both desktop and mobile

I also didn't know how to create a partial, i'll just try it out at another time

**Comment by Bedrock02** [comment]
DON'T MERGE [WIP]

**Comment by dvidsilva** [comment]
sorry @Bedrock02  dropped the ball, I'll merge this tomorrow

**Comment by dvidsilva** [comment]
If we add the read more button to the template would it work across all content? the new EOs are missing it

**Comment by fvntr** [comment]
definitely needs to be refactored and included in both eo and issues templates

**Pull request merged**
